version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing package dependencies...
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'